import torch
import glob
import random
import numpy as np
import os
from tqdm import tqdm


class OCTEmbededFeatsDataset(torch.utils.data.Dataset):
    """
    Dataset for OCT embedded features, following ICMIL's EmbededFeatsDataset pattern.
    Loads .npy files generated by retinal_feature_extraction_icmil.py
    Supports both binary (num_cls=2) and 4-class (num_cls=4) classification.
    """
    def __init__(self, path, mode='train', level=0, num_cls=2):
        """
        Args:
            path:    Root path containing train/val/test folders
            mode:    'train', 'val', or 'test'
            level:   Not used for OCT (kept for compatibility with ICMIL)
            num_cls: 2 for binary (NORMAL vs DISEASE), 4 for multi-class
        """
        super().__init__()
        self.mode = mode
        self.num_cls = num_cls
        self.data = []
        self.label = []

        # Class mapping — depends on num_cls
        if num_cls == 2:
            self.class_map = {'CNV': 1, 'DME': 1, 'DRUSEN': 1, 'NORMAL': 0}
        else:
            self.class_map = {'CNV': 0, 'DME': 1, 'DRUSEN': 2, 'NORMAL': 3}

        # ------------------------------------------------------------------ #
        #  TRAIN / VAL                                                         #
        # ------------------------------------------------------------------ #
        if mode == 'train' or mode == 'val':

            # Collect all files from every class
            filenames = []
            for class_name in self.class_map.keys():
                pattern = os.path.join(path, 'train', class_name, '*_resnet1024_feats.npy')
                class_files = sorted(glob.glob(pattern))
                filenames.extend(class_files)

            # Undersample NORMAL only for binary classification
            if num_cls == 2:
                normal_files = [f for f in filenames if os.sep + 'NORMAL' + os.sep in f]
                disease_files = [f for f in filenames if os.sep + 'NORMAL' + os.sep not in f]

                random.seed(552)
                normal_files = random.sample(normal_files, min(len(disease_files), len(normal_files)))
                filenames = normal_files + disease_files

            else:
                # 4-class: use all files, just set seed before shuffle
                random.seed(552)

            random.shuffle(filenames)
            random.seed()

            # 90/10 train-val split
            n_train = int(0.9 * len(filenames))

            selected_files = filenames[:n_train] if mode == 'train' else filenames[n_train:]

            # Load data
            print(f'Loading {mode} data...')
            for fname in tqdm(selected_files, desc=f'Loading {mode} set'):
                npy = np.load(fname)
                self.data.append(npy)
                parts = fname.split(os.sep)
                class_name = parts[-2]
                self.label.append(self.class_map[class_name])

        # ------------------------------------------------------------------ #
        #  TEST                                                                #
        # ------------------------------------------------------------------ #
        elif mode == 'test':

            if num_cls == 2:
                # Undersample NORMAL to balance test set
                normal_files = []
                disease_files = []
                for class_name in self.class_map.keys():
                    pattern = os.path.join(path, 'test', class_name, '*_resnet1024_feats.npy')
                    files = sorted(glob.glob(pattern))
                    if class_name == 'NORMAL':
                        normal_files.extend(files)
                    else:
                        disease_files.extend(files)

                random.seed(42)
                normal_files = random.sample(normal_files, min(len(disease_files), len(normal_files)))
                random.seed()
                filenames = normal_files + disease_files

            else:
                # 4-class: use all test files
                filenames = []
                for class_name in self.class_map.keys():
                    pattern = os.path.join(path, 'test', class_name, '*_resnet1024_feats.npy')
                    class_files = sorted(glob.glob(pattern))
                    filenames.extend(class_files)

            print(f'Loading {mode} data...')
            for fname in tqdm(filenames, desc=f'Loading {mode} set'):
                npy = np.load(fname)
                self.data.append(npy)
                parts = fname.split(os.sep)
                class_name = parts[-2]
                self.label.append(self.class_map[class_name])

        # ------------------------------------------------------------------ #
        #  SUMMARY                                                             #
        # ------------------------------------------------------------------ #
        print(f'{mode} set: {len(self.data)} samples')
        if num_cls == 2:
            n_normal = self.label.count(0)
            n_disease = len(self.label) - n_normal
            print(f'  → NORMAL: {n_normal} | DISEASE: {n_disease}')
        else:
            # Reverse map: for 4-class each label maps to a unique class name
            reverse_map = {v: k for k, v in self.class_map.items()}
            for cls_idx in sorted(set(self.label)):
                print(f'  → {reverse_map[cls_idx]}: {self.label.count(cls_idx)}')

    # ---------------------------------------------------------------------- #

    def __len__(self):
        return len(self.label)

    def augment(self, feats):
        """Shuffle instances within a bag"""
        np.random.shuffle(feats)
        return feats

    def __getitem__(self, index):
        """
        Returns:
            feats: numpy array of shape (num_instances, 1024)
            label: int
                   binary  → 0=NORMAL, 1=DISEASE (CNV/DME/DRUSEN)
                   4-class → 0=CNV, 1=DME, 2=DRUSEN, 3=NORMAL
        """
        return self.augment(self.data[index]), self.label[index]


# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--data_path', default='/kaggle/working/Retinal', type=str)
    parser.add_argument('--num_cls', default=2, type=int)
    args = parser.parse_args()

    print(f"\nTesting OCTEmbededFeatsDataset (num_cls={args.num_cls})...")

    print("\n=== Train Set ===")
    trainset = OCTEmbededFeatsDataset(args.data_path, mode='train', num_cls=args.num_cls)

    print("\n=== Val Set ===")
    valset = OCTEmbededFeatsDataset(args.data_path, mode='val', num_cls=args.num_cls)

    print("\n=== Test Set ===")
    testset = OCTEmbededFeatsDataset(args.data_path, mode='test', num_cls=args.num_cls)

    print("\n=== Sample Check ===")
    feats, label = trainset[0]
    print(f"Features shape: {feats.shape}")
    print(f"Label: {label}")
    if args.num_cls == 2:
        print(f"Label name: {'NORMAL' if label == 0 else 'DISEASE'}")
    else:
        reverse_map = {v: k for k, v in trainset.class_map.items()}
        print(f"Label name: {reverse_map[label]}")